### ISSUE TITLE
Some cover not detected

### ISSUE THREAD

**Issue by cvermot** [WiwiWillou/tydom2mqtt#20]
Hi,

I have a Delta Dore Hub with 2 covers. I use this plugin with good results since some mounth. Recently, I'm no longer able to control one of my cover, the second one is operating as expected. I have tried to uninstall plugins and MQTT, MQTT discovery is on and found my functional cover. I'm able to command both cover from Delta Dore app. Here is my log :

> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> TYDOM WEBSOCKET CONNECTION INITIALISING....                     
> Building headers, getting 1st handshake and authentication....
> Upgrading http connection to websocket....
> Attempting websocket connection with tydom hub.......................
> Host Target :
> 192.168.1.116
> Tydom Client is connected to websocket and ready !
> Requesting 1st data...
> >>>>>>>>>> Sending to tydom client..... GET /info
> ##################################
> ##################################
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> >>>>>>>>>> Sending to tydom client..... GET /configs/file
> >>>>>>>>>> Sending to tydom client..... GET /devices/data
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> Incoming message type : Info detected
> Incoming data parsed successfully !
> <<<<<<<<<< Receiving from tydom_client...
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> Incoming message type : config detected
> Configuration updated
> Incoming data parsed successfully !
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> Incoming message type : data detected
> 1554930574 not in dic device_name
> 1554930574 not in dic device_type
> Incoming data parsed successfully !
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> Incoming message type : data detected
> 1554930574 not in dic device_name
> 1554930574 not in dic device_type
> Sensor created / updated :  device_id_tydom__Volet_Jardin 1557594030
> Sensor created / updated :  endpoint_id_tydom__Volet_Jardin 1557594030
> Sensor created / updated :  id_tydom__Volet_Jardin 1557594030_1557594030
> Binary sensor created / updated :  thermicDefect_tydom__Volet_Jardin False
> Sensor created / updated :  position_tydom__Volet_Jardin 93
> Binary sensor created / updated :  onFavPos_tydom__Volet_Jardin False
> Binary sensor created / updated :  obstacleDefect_tydom__Volet_Jardin False
> Binary sensor created / updated :  intrusion_tydom__Volet_Jardin False
> Binary sensor created / updated :  battDefect_tydom__Volet_Jardin False
> Cover created / updated :  Volet Jardin 1557594030_1557594030 93
> Incoming data parsed successfully !
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>> Sending to tydom client..... POST /refresh/all
> <<<<<<<<<< Receiving from tydom_client...
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> Incoming message type : data detected
> 1554930574 not in dic device_name
> 1554930574 not in dic device_type
> Sensor created / updated :  device_id_tydom__Volet_Jardin 1557594030
> Sensor created / updated :  endpoint_id_tydom__Volet_Jardin 1557594030
> Sensor created / updated :  id_tydom__Volet_Jardin 1557594030_1557594030
> Binary sensor created / updated :  position_tydom__Volet_Jardin 0
> Cover created / updated :  Volet Jardin 1557594030_1557594030 0
> Incoming data parsed successfully !
> <<<<<<<<<< Receiving from tydom_client...
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> Incoming message type : data detected
> 1554930574 not in dic device_name
> 1554930574 not in dic device_type
> Sensor created / updated :  device_id_tydom__Volet_Jardin 1557594030
> Sensor created / updated :  endpoint_id_tydom__Volet_Jardin 1557594030
> Sensor created / updated :  id_tydom__Volet_Jardin 1557594030_1557594030
> Sensor created / updated :  position_tydom__Volet_Jardin 88

I think that lines :
1554930574 not in dic device_name
1554930574 not in dic device_type

indicate some problems ? Any idea ?

**Comment by clementleroy** [comment]
Hi ! 
If you could run [this script](https://github.com/mgcrea/node-tydom-client) and run 
`npx tydom-client request /configs/file /devices/data /devices/meta /devices/cmeta --file tydom_output.json --username 001A25XXXXX --password YouPassword` 
and send us the file generated we may have a better chance to help you resolve your bug. 
By any means have you renamed your cover ? It may be safer not to use accent.

**Comment by cvermot** [comment]
Hi,

Thank you for your answer !

Here is the generated JSON (I renamed it from .JSON to .LOG in order to be able to upload it to GitHub). I confirm that I have no accents on my devices names (screen shot of the Tydom app where you can see my devices names). I effectively rename the problematic cover when he became not available, without any reappearance.

[tydom_output.log](https://github.com/mrwiwi/tydom2mqtt/files/5705405/tydom_output.log)
[Screenshot_20201216-214329](https://user-images.githubusercontent.com/17338322/102404334-de081900-3fe7-11eb-834e-4bdb3cd1cc47.png)

**Comment by clementleroy** [comment]
As you can see here 
``` "endpoints": [
      {
        "id_endpoint": 1543499007,
        "first_usage": "shutter",
        "id_device": 1543499007,
        "name": "Porte Fenetre",
        "anticipation_start": false,
        "picto": "picto_shutter",
        "last_usage": "shutter"
      },
      {
        "id_endpoint": 1554930574,
        "first_usage": "shutter",
        "id_device": 1554930575,
        "name": "Porte Fenetre",
        "anticipation_start": false,
        "picto": "picto_shutter",
        "last_usage": "shutter"
      },
      {
        "id_endpoint": 1557594030,
        "first_usage": "shutter",
        "id_device": 1557594030,
        "name": "Volet Jardin",
        "anticipation_start": false,
        "picto": "picto_shutter",
        "last_usage": "shutter"
      }
    ],
```
Your tydom returned 3 covers : 1543499007, 1554930574 and 1557594030. The first one is duplicated. And I guess it may be the cause of your trouble. 
Maybe you could try to remove the "Porte Fenetre" cover from your tydom and see if the tydom remove both of them in the API response and then add it again. 
Otherwise, you may need te reset you tydom to remove this ghost cover.

**Comment by cvermot** [comment]
Hi,

It finally rework alone... don't know why...
