### ISSUE TITLE
Missing type

### ISSUE THREAD

**Issue by cob94440** [WiwiWillou/tydom2mqtt#23]
Bonjour J'ai une box tydom avec des dvi de fenêtre kline.
En installant le plugin sous docker il me manque les types. du coup ils ne remontent pas dans mqtt. Comment et où les ajouter? de quoi as tu besoin?

Merci d'avance.
Ci dessous il y a 2 types mais il en manque d'autres.
Je reçois les volets roulants la semaine prochaine il faudra peut être d'autres types.

Incoming message type : data detected

1611160982 not in dic device_name

1611160982 not in dic device_type

Incoming data parsed successfully !

>>>>>>>>>> Sending to tydom client..... POST /refresh/all

<<<<<<<<<< Receiving from tydom_client...

>>>>>>>>>> Sending to tydom client..... POST /refresh/all

<<<<<<<<<< Receiving from tydom_client...

>>>>>>>>>> Sending to tydom client..... POST /refresh/all

<<<<<<<<<< Receiving from tydom_client...

>>>>>>>>>> Sending to tydom client..... POST /refresh/all

<<<<<<<<<< Receiving from tydom_client...

<<<<<<<<<< Receiving from tydom_client...

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Incoming message type : data detected

1611170124 not in dic device_name

1611170124 not in dic device_type

Incoming data parsed successfully !

>>>>>>>>>> Sending to tydom client..... POST /refresh/all

**Comment by cob94440** [comment]
Normalement j'ai ajouté les portes, fénetres et volets kline. Pourrais tu valider stp

**Comment by cob94440** [comment]
A priori c'est bcp.mieux. il manque pour les volets les commandes UP. Le down et stop fonctionnent. Je ne vois pas de slider pour ouvrir a un certain pourcentage aussi. Une idée ?

**Comment by TRSATOC** [comment]
Je confirme que les les capteurs K-Line sont bien disponibles, merci pour ton travail!
