### ISSUE TITLE
Question: does it work with Calybox (pilot wires)?

### ISSUE THREAD

**Issue by fmartinou** [WiwiWillou/tydom2mqtt#37]
Hi,

Not an issue, just a question (I cannot find a clear answer by myself).

I'm planning to buy a Tydom 1.0 but I'm not sure whether it will work with 🤔 .
Does this app work for Calybox devices (220, 230...) controlling heaters using pilot wires (aka "fil pilote")?
I mean, would I be able to set pilot wire orders (off, antifrost, eco, comfort) for every controlled zone independently?

Thank you for your answer and by the way; many thanks for this great project!

**Comment by mrwiwi** [comment]
Hi, i don't know ! But if tydom box is working with, there is a good chance ! At this point i don't have many delta dore products...

After that if it's not exposed by tydom2mqtt you can contribute by creating the handler !
